[versions]
aurora = "2.0-20231104.160413-6"
buildconfig = "5.4.0"
compose = "1.6.11"
coroutines = "1.8.1"
cryptohash = "1.0.2"
detekt = "1.23.6"
flowext = "0.8.1"
jna = "5.14.0"
jsystemthemedetector = "3.9.1"
klogging = "0.6.1"
kotlin = "2.0.0"
kotlin-csv = "1.9.3"
kotlinx-datetime = "0.6.0"
ktgithub = "b02824c1ba"
ktor = "2.3.12"
lwjgl = "3.3.4"
slf4j = "2.0.13"
voyager = "1.0.0"
windowstyler = "0.3.2"

[libraries]
aurora-component = { module = "org.pushing-pixels:aurora-component", version.ref = "aurora" }
aurora-theming = { module = "org.pushing-pixels:aurora-theming", version.ref = "aurora" }
aurora-window = { module = "org.pushing-pixels:aurora-window", version.ref = "aurora" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

crypto-cryptohash = { module = "com.appmattus.crypto:cryptohash", version.ref = "cryptohash" }

detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

flowext = { module = "io.github.hoc081098:FlowExt", version.ref = "flowext" }

jna = { module = "net.java.dev.jna:jna-jpms", version.ref = "jna" }
jna-platform = { module = "net.java.dev.jna:jna-platform-jpms", version.ref = "jna" }

jsystemthemedetector = { module = "com.github.Dansoftowner:jSystemThemeDetector", version.ref = "jsystemthemedetector" }

klogging-jvm = { module = "io.klogging:klogging-jvm", version.ref = "klogging" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

kotlincsv = { module = "com.github.doyaaaaaken:kotlin-csv", version.ref = "kotlin-csv" }

ktgithub = { module = "com.github.russellbanks.KtGitHub:KtGitHub", version.ref = "ktgithub" }

ktor-client-java = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }

lwjgl-core = { module = "org.lwjgl:lwjgl", version.ref = "lwjgl" }
lwjgl-nativefiledialogs = { module = "org.lwjgl:lwjgl-nfd", version.ref = "lwjgl" }

slf4j-nop = { module = "org.slf4j:slf4j-nop", version.ref = "slf4j" }

voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager-screenmodel = { module = "cafe.adriel.voyager:voyager-screenmodel", version.ref = "voyager" }
voyager-tabNavigator = { module = "cafe.adriel.voyager:voyager-tab-navigator", version.ref = "voyager" }

windowstyler = { module = "com.mayakapps.compose:window-styler", version.ref = "windowstyler" }

[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
